#!/usr/bin/env bash
dir=$(cd `dirname $0` && pwd)
cd ${dir}

mysql -uerasmusline -porange < p8statsdw.sql

./populateDB.php

mysql -uerasmusline -porange p8statsdw < fact_efficiency_2010_2s.sql

echo ""