#!/usr/bin/env bash
dir=$(cd `dirname $0` && pwd)
cd ${dir}


echo "drop database if exists erasmusline; create database erasmusline;" | mysql -uerasmusline -porange
mysql -uerasmusline -porange erasmusline < erasmusline.sql
echo ""