#!/usr/bin/env php
<?php
$ipath = get_include_path();
set_include_path($ipath.":".dirname(__FILE__)."/../../");

require_once("lib/System/Daemon.php");                 // Include the Class
require_once("lib/LooPHP/Autoload.php");
LooPHP_Autoloader::register();

$configfile = dirname(__FILE__).'/config.json';
$options = json_decode(file_get_contents($configfile),true);
if(!isset($options)){
	throw new Exception("Invalid JSON: ${configfile}");
}


// Setup
$dconfig = array_merge($options['daemonconfig'],array(
    'appDir' => dirname(__FILE__),
    'appDescription' => 'Slave STATS Server',
    'sysMaxExecutionTime' => '0',
    'sysMaxInputTime' => '0',
    'sysMemoryLimit' => '1024M',
    'appRunAsGID' => posix_getegid(),
    'appRunAsUID' => posix_getuid(),
    'logLocation' => '/tmp/erasmusline/statsd_slave/statsd_slave.log',
    'appPidLocation' => '/tmp/erasmusline/statsd_slave/statsd_slave.pid',
));

mkdir(dirname($dconfig['logLocation']),0777,true);

//print_r($dconfig);

System_Daemon::setOptions($dconfig);  // Minimum configuration
System_Daemon::start();              // Spawn Deamon!

include "StatsdSlave.php";

$daemon = new StatsdSlave($options);

System_Daemon::stop();
?>