#!/usr/bin/env bash

dir=$(cd `dirname $0` && pwd)
cd ${dir}

regex="\.php$"

Dirlist=$(find . -type f)
for file in $Dirlist ; do
	if [[ ${file} =~ $regex ]];
	then
		echo "Test: ${file}"
		php "./${file}"
	fi
done