#!/usr/bin/env php
<?php
$ipath = get_include_path();
$sep = DIRECTORY_SEPARATOR;
$path = realpath(dirname(__FILE__)."${sep}..${sep}..${sep}");
set_include_path($ipath.":".$path);

date_default_timezone_set('UTC');

require_once("lib/System/Daemon.php");                 // Include the Class
require_once("lib/LooPHP/Autoload.php");
LooPHP_Autoloader::register();

require_once('lib/JSONConfig.php');
$options = JSONConfig::load(dirname(__FILE__),
					'config');

// Setup
$dconfig = array_merge($options['daemonconfig'],array(
    'appDir' => dirname(__FILE__),
    'appDescription' => 'Message Queue',
    'sysMaxExecutionTime' => '0',
    'sysMaxInputTime' => '0',
    'sysMemoryLimit' => '1024M',
    'appRunAsGID' => posix_getegid(),
    'appRunAsUID' => posix_getuid(),
    'logLocation' => '/tmp/erasmusline/mqueued/mqueued.pid',
    'appPidLocation' => '/tmp/erasmusline/mqueued/mqueued.pid',
    'usePEAR' => false,
));

if(!is_dir(dirname($dconfig['logLocation'])))
	mkdir(dirname($dconfig['logLocation']),0777,true);

//print_r($dconfig);

System_Daemon::setOptions($dconfig);  // Minimum configuration
System_Daemon::start();              // Spawn Deamon!

include "MQueued.php";

$daemon = new MQeued($options);

System_Daemon::stop();
?>