#!/usr/bin/env php
<?php
$ipath = get_include_path();
$sep = DIRECTORY_SEPARATOR;
$path = realpath(dirname(__FILE__)."${sep}..${sep}..${sep}");
set_include_path($ipath.":".$path);

date_default_timezone_set('UTC');

require_once("lib/System/Daemon.php");                 // Include the Class
require_once("lib/LooPHP/Autoload.php");
LooPHP_Autoloader::register();

$configfile = dirname(__FILE__).$sep.'config.json';
$options = json_decode(file_get_contents($configfile),true);
if(!isset($options)){
	throw new Exception("Invalid JSON: ${configfile}");
}
		
// Setup
$dconfig = array_merge($options['daemonconfig'],array(
    'appDir' => dirname(__FILE__),
    'appDescription' => 'Master STATS Server',
    'sysMaxExecutionTime' => '0',
    'sysMaxInputTime' => '0',
    'sysMemoryLimit' => '1024M',
    'appRunAsGID' => posix_getegid(),
    'appRunAsUID' => posix_getuid(),
    'logLocation' => '/tmp/erasmusline/statsd_master/statsd_master.log',
    'appPidLocation' => '/tmp/erasmusline/statsd_master/statsd_master.pid',
    'usePEAR' => false,
));

if(!is_dir(dirname($dconfig['logLocation'])))
	mkdir(dirname($dconfig['logLocation']),0777,true);

//print_r($dconfig);

System_Daemon::setOptions($dconfig);  // Minimum configuration
System_Daemon::start();              // Spawn Deamon!

include "StatsdMaster.php";

$daemon = new StatsdMaster($options);

System_Daemon::stop();
?>